version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: animeapp
      POSTGRES_PASSWORD: "vpFhK_wl0r0OJspRJXfmUtUIOTS8EgCI"
    volumes:
      - animeapp_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "w82cUxsAILqoxfRqhMwjgeX5OLVEZZHA"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  animeapp_data:
